"""drop owasp column from levels

Revision ID: 6f618c2c8206
Revises: a147b47f17ab
Create Date: 2026-04-20 22:39:21.639084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f618c2c8206'
down_revision: Union[str, Sequence[str], None] = 'a147b47f17ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'owasp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('owasp', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
